### PR TITLE
examples for: increment-decrement, distance-1d and distance-2d

### PR DESCRIPTION
**Pull request by eXodiquas**
I translated 3 examples from the processing.org examples into sketching examples. Namely: increment-decrement, distance1d and distance2d. I tried to stay as close as possible to the original. If you want me to make it more idiomatic, I am happy to do so.

### CODE REVIEW

**Comment by soegaard** [comment]
This looks great. 

Apropos idiomatic, I think I have used used `:=` instead of `set!` in most examples.

I'll merge. Are you up for adding the examples to the manual? 
Besides adding a new section for basic/math examples, you'll need to move the files into the manual-examples folder.

https://github.com/soegaard/sketching/blob/main/sketching-doc/sketching-doc/manual-sketching.scrbl#L7229

**Comment by eXodiquas** [comment]
I will try and add the examples to the manual. I will also rename the example files to match the existing ones.

**Comment by soegaard** [comment]
@all-contriburs please add @eXodiquas  for code and examples

**Comment by soegaard** [comment]
@all-contributors please add @eXodiquas for code and examples

**Pull request merged**
