### PR TITLE
Add math examples for: remap, sine-cosine, sine-wave, sine. Plus file management

### PR DESCRIPTION
**Pull request by eXodiquas**
I added some more examples, namely: 
- Remap
- Sine
- Sine Cosine
- Sine Wave

And I renamed the example files to match the remaining files. I added the Math subsection in the scribble file and I added all the examples to the documentation folder. I also changed all my uses of 'set!' to ':='.

This is my first time working with scribble. I think I've done everything correct, but maybe someone should take a look at what I did there.

### CODE REVIEW

**Comment by soegaard** [comment]
Looks fine to me at first sight. I'll check later and see if the built documentation looks as expected.

**Comment by soegaard** [comment]
The document builds fine.

The error you isn't due to your changes.
Normally Github rebuilds the documentation and uploads them to soegaard.github.io/sketching .
But it seems the permissions doesn't work for pull requests yet.
The documentation on docs.racket-lang.org will work.

I'll fix the permission problem some time this week.

**Comment by soegaard** [comment]
Thanks again for porting the examples.

**Comment by eXodiquas** [comment]
Aye aye, I think you did a great job with this project and I will likely port more examples in the future.

**Comment by soegaard** [comment]
Thanks for the kind words. I'll look forward to more examples.

**Pull request merged**
